/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { McpBindRequest, McpBindResult, McpBoundResult, McpCatalog, McpManagerResult, McpRemoveRequest, McpRemoveResult, McpServerToolsRequest, McpServerToolsResult, McpUnbindRequest, McpUnbindResult, McpUpsertRequest, McpUpsertResult } from '@deepseek-ai/dsh-mcp-manager/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d63704d616e61676572 {
    bind: (agentId: SessionId, request: McpBindRequest) => Promise<RemoteResult<McpBindResult>>
    bound: (agentId: SessionId) => Promise<RemoteResult<McpBoundResult>>
    deleteServer: (request: McpRemoveRequest) => Promise<RemoteResult<McpRemoveResult>>
    list: () => Promise<RemoteResult<McpManagerResult<McpCatalog>>>
    serverTools: (request: McpServerToolsRequest) => Promise<RemoteResult<McpServerToolsResult>>
    unbind: (agentId: SessionId, request: McpUnbindRequest) => Promise<RemoteResult<McpUnbindResult>>
    upsert: (request: McpUpsertRequest) => Promise<RemoteResult<McpUpsertResult>>
  }
  interface TypertRemoteMap {
    'mcpManager/bind': (agentId: SessionId, request: McpBindRequest) => Promise<RemoteResult<McpBindResult>>
    'mcpManager/bound': (agentId: SessionId) => Promise<RemoteResult<McpBoundResult>>
    'mcpManager/deleteServer': (request: McpRemoveRequest) => Promise<RemoteResult<McpRemoveResult>>
    'mcpManager/list': () => Promise<RemoteResult<McpManagerResult<McpCatalog>>>
    'mcpManager/serverTools': (request: McpServerToolsRequest) => Promise<RemoteResult<McpServerToolsResult>>
    'mcpManager/unbind': (agentId: SessionId, request: McpUnbindRequest) => Promise<RemoteResult<McpUnbindResult>>
    'mcpManager/upsert': (request: McpUpsertRequest) => Promise<RemoteResult<McpUpsertResult>>
  }
  interface TypertRemoteNamespaceMap {
    'mcpManager': TypertRemoteNamespace$6d63704d616e61676572
  }
  interface TypertRemoteScopeMap {
    'agent:mcpManager/bind': (request: McpBindRequest) => Promise<RemoteResult<McpBindResult>>
    'agent:mcpManager/bound': () => Promise<RemoteResult<McpBoundResult>>
    'agent:mcpManager/unbind': (request: McpUnbindRequest) => Promise<RemoteResult<McpUnbindResult>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
